### ISSUE TITLE
考试开始倒计时错误地显示为考试结束倒计时

### ISSUE THREAD

**Issue by MF-Dust** [ProjectCampus-CH/dsz-exam-showboard-next#15]
![image](https://github.com/user-attachments/assets/05a1fd22-01d1-46ae-8d82-ee5352e4b790)

**Comment by MF-Dust** [comment]
![image](https://github.com/user-attachments/assets/30e70a01-80a8-4e34-836c-29ace097de9a)

**Comment by MKStoler4096** [comment]
这个是因为一个遗留BUG，等我修修

但是也没有科目15分钟考完吧（？）

**Comment by MKStoler4096** [comment]
逻辑是我合并的（）不打算撤销了，反正只要考试时间长于15分钟就没有这个bug（）
下一次改大史的时候再还原逻辑吧，懒得修了，专心搞UI开发（）
