### ISSUE TITLE
使用GUI设置配置文件   优先率低

### ISSUE THREAD

**Issue by belugaQAQ** [ProjectCampus-CH/dsz-exam-showboard-next#24]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ProjectCampus-CH/dsz-exam-showboard-next?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ProjectCampus-CH/dsz-exam-showboard-next/issues?q=label%3A新功能) 确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出考试看板 Next 的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/zh-cn/latest/dev/plugins/create-project/)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

使用考试看板next的一般都是学生，老师弄不好配置文件

### 想要实现或优化的功能

使用GUI（方便，简约）设置配置文件

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by belugaQAQ** [comment]
可能或者设置小倒计时来进行小测试

**Comment by MKStoler4096** [comment]
其实有个Python简易版的（）但是考虑转向C#就没发（）

**Comment by belugaQAQ** [comment]
> 其实有个Python简易版的（）但是考虑转向C#就没发（）

能不能单独做个小程序，来给老师用？

**Comment by belugaQAQ** [comment]
很需要

**Comment by MKStoler4096** [comment]
有的，等我转移一下仓库

**Comment by MKStoler4096** [comment]
https://github.com/ProjectCampus-CH/DSZExamShowBoardEditor/releases/tag/0.0.1 这个便是

**Comment by belugaQAQ** [comment]
太好辣

**Comment by belugaQAQ** [comment]
不是，你真不打算改了
那劣质东东不打算重做了？

**Comment by MKStoler4096** [comment]
等着吧......

**Comment by fhzit** [comment]
你就可能需要的是这个[GUI编辑器](https://github.com/ProjectCampus-CH/DSZExamShowBoardEditor)
