### ISSUE TITLE
考试都已经进行到下一堂了，“当前科目”处还显示上一堂“结束”

### ISSUE THREAD

**Issue by wjj-8283** [ProjectCampus-CH/dsz-exam-showboard-next#25]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ProjectCampus-CH/dsz-exam-showboard-next?include_prereleases&style=flat-square&label=) ，并看过[最新提交](https://github.com/ProjectCampus-CH/dsz-exam-showboard-next/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ProjectCampus-CH/dsz-exam-showboard-next/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

上一堂结束，下一堂开始时，自动切换到下一堂
![2024-11-03 15-04-51Z](https://github.com/user-attachments/assets/d5ab33d1-97c6-4205-9ed3-90f8081ca2b1)

### 实际结果

实际上，在下一堂开始时，并没有自动刷新
![2024-11-03 15-00-46Z](https://github.com/user-attachments/assets/e88472e5-f0e0-4df4-9d7e-47a94a1ab0f6)

### 重现步骤

添加一场一天有好几堂的考试，然后坐和放宽，等待他们全部结束

### 堆栈跟踪（可选）

```shell
没有
```

### 应用版本

1.1.3最新dev构建

### 操作系统版本

10.0.26100.1150，Windows 11 IoT企业版LTSC

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by wjj-8283** [comment]
人工退回主界面并重新进入可以缓解，但是肯定没有自动刷新优雅

**Comment by MKStoler4096** [comment]
> 人工退回主界面并重新进入可以缓解，但是肯定没有自动刷新优雅

有自动刷新的，我设的1分钟后，如果没有更新到1.1.3看看。

**Comment by wjj-8283** [comment]
我直接用的dev分支源码自己build的，好像还是没有

**Comment by wjj-8283** [comment]
我先从actions中间下载看看

**Comment by MKStoler4096** [comment]
（）从 main 生成，dev 很抽象……
