### ISSUE TITLE
针对一些显示问题的优化建议

### ISSUE THREAD

**Issue by wjj-8283** [ProjectCampus-CH/dsz-exam-showboard-next#27]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ProjectCampus-CH/dsz-exam-showboard-next?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ProjectCampus-CH/dsz-exam-showboard-next/issues?q=label%3A新功能) 确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出考试看板 Next 的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/zh-cn/latest/dev/plugins/create-project/)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

最新的版本考试列表存在显示问题，如下图：
正常的科目长度下：
![2024-11-06 22-26-25Z](https://github.com/user-attachments/assets/c24a85cf-2a4c-4261-88b7-967928bd52ed)
科目长度稍长下：
![2024-11-06 22-24-33Z](https://github.com/user-attachments/assets/f582eeb8-7d77-4401-a843-a883c7e2033a)

### 想要实现或优化的功能

![2024-11-06 22-29-21Z](https://github.com/user-attachments/assets/9e0e51f5-251f-4a75-8f69-741df0231235)
如图

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
我考虑考虑

在这之前可以先通过改系统缩放曲线救国？

**Comment by wjj-8283** [comment]
![2024-11-07 12-25-13Z](https://github.com/user-attachments/assets/c4e44c9e-2dd4-4564-8486-41d551774928)

**Comment by MKStoler4096** [comment]
行吧，我看看，主要是想把这个整合进设置里面（）

**Comment by wjj-8283** [comment]
期待，虽然已经高三了，用这个软件用不了几次了（）

**Comment by MKStoler4096** [comment]
大概完工了（）过会测一下

**Comment by wjj-8283** [comment]
我编译测试过了，没有多大问题，但是一个小建议，绿色有点太深了（背景可是黑的！），建议调浅一点

**Comment by wjj-8283** [comment]
我自己改了一下并交了pr

**Comment by MKStoler4096** [comment]
ok，准了
很好的建议，我这边也偏深，结果老铁你先我一步（）

**Comment by Jursin** [comment]
这个是我的问题，当时提交Pr后就发现了，内边距设大了，应该不用内边距，先只在我复刻的项目里修复了，准备还修改一些其他的再一起提交Pr的😂
